language: python
python:
  - "3.6"
  - "3.8"
# command to install dependencies
install:
  - pip install --progress-bar off -r requirements.txt
  - pip install -e .
# command to run tests
script:
  - pytest
